ALTER TABLE "AdSlot" ADD COLUMN IF NOT EXISTS "viewsSeeker" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "AdSlot" ADD COLUMN IF NOT EXISTS "viewsEmployer" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "AdSlot" ADD COLUMN IF NOT EXISTS "clicksSeeker" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "AdSlot" ADD COLUMN IF NOT EXISTS "clicksEmployer" INTEGER NOT NULL DEFAULT 0;
